name: Build Nearby Share for Linux

on:
  push:
    paths:
      - ".github/workflows/builder.yml"
      - "README.md"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Essentials
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: tmate
        run: |
          brew install tmate \
          tmate
