name: Build Nearby Share for Linux

on:
  push:
    paths:
      - ".github/workflows/builder.yml"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Essentials
        run: |
          sudo apt update
          sudo apt install -y git bazel-bootstrap clang gcc-mingw-w64 gcc-multilib libasound2-dev libcups2-dev \
              libdbus-1-dev libfontconfig-dev libfreetype-dev libgl-dev libgnutls28-dev \
              libgphoto2-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev \
              libosmesa6-dev libpcap-dev libpulse-dev libsane-dev libsdl2-dev \
              libudev-dev libunwind-dev libusb-1.0-0-dev libvulkan-dev libx11-dev \
              libxcomposite-dev libxcursor-dev libxext-dev libxfixes-dev libxi-dev \
              libxrandr-dev libxrender-dev ocl-icd-opencl-dev samba-dev

      - name: Compile NearbyShare
        run: |
          git clone https://github.com/google/nearby/ nearby
          cd nearby
          git submodule update --init --recursive
          CC=clang CXX=clang++ bazel build -s --check_visibility=false //connections:core  --spawn_strategy=standalone --verbose_failures
          tar -cvf build.tar build
          xz -z build.tar
          mv build.tar.xz /opt/

      - name: Upload to GitHub Artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /opt/build.tar.xz
          tag: latest
          overwrite: true
          body: "New Release."
